In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[7.3470e-39, 1.0653e-38, 1.0194e-38],
        [4.6838e-39, 8.4489e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5410, 0.7700, 0.8208],
        [0.7677, 0.9844, 0.7273],
        [0.1847, 0.3168, 0.4719],
        [0.4073, 0.5266, 0.6192],
        [0.8236, 0.9313, 0.1171]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7947, -1.1218,  0.8069],
        [ 0.6787,  0.3721,  2.3636],
        [ 0.0931, -0.6516, -2.2562],
        [ 0.6501, -0.6530, -0.3184],
        [-0.0828,  0.2241, -0.0444]])


In [8]:
print(x.size())

torch.Size([5, 3])
